version: "3.5"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prescription_front
    ports:
      - "80:3000"
    networks:
      - applicant_registration

networks:
  applicant_registration:
    external: true
